 export const stateList =[
    [ 'Andhra Pradesh', 'AP' ],
    [ 'Arunachal Pradesh', 'AR' ],
    [ 'Assam', 'AS' ],
    [ 'Bihar', 'BR' ],
    [ 'Chhattisgarh', 'CG' ],
    [ 'Goa', 'GA' ],
    [ 'Gujarat', 'GJ' ],
    [ 'Haryana', 'HR' ],
    [ 'Himachal Pradesh', 'HP' ],
    [ 'Jammu and Kashmir', 'JK' ],
    [ 'Jharkhand', 'JH' ],
    [ 'Karnataka', 'KA' ],
    [ 'Kerala', 'KL' ],
    [ 'Madhya Pradesh', 'MP' ],
    [ 'Maharashtra', 'MH' ],
    [ 'Manipur', 'MN' ],
    [ 'Meghalaya', 'ML' ],
    [ 'Mizoram', 'MZ' ],
    [ 'Nagaland', 'NL' ],
    [ 'Orissa', 'OR' ],
    [ 'Punjab', 'PB' ],
    [ 'Rajasthan', 'RJ' ],
    [ 'Sikkim', 'SK' ],
    [ 'Tamil Nadu', 'TN' ],
    [ 'Tripura', 'TR' ],
    [ 'Uttarakhand', 'UK' ],
    [ 'Uttar Pradesh', 'UP' ],
    [ 'West Bengal', 'WB' ],
    [ 'Telangana', 'TS' ],
    [ 'Andaman and Nicobar Islands', 'AN' ],
    [ 'Chandigarh', 'CH' ],
    [ 'Dadra and Nagar Haveli', 'DH' ],
    [ 'Daman and Diu', 'DD' ],
    [ 'Delhi', 'DL' ],
    [ 'Lakshadweep', 'LD' ],
    [ 'Pondicherry', 'PY' ]
  ]

export const gameList = [
  [ 'Super Mario 64 DS', 'c01' ],
  [ 'Lumines: Puzzle Fusion', 'c02' ],
  [ 'WarioWare Touched!', 'c03' ],
  [ 'Hot Shots Golf: Open Tee', 'c04' ],
  [ 'Spider-Man 2', 'c05' ],
  [ 'The Urbz: Sims in the City', 'c06' ],
  [ 'Ridge Racer', 'c07' ],
  [ 'Metal Gear Ac!d', 'c08' ],
  [ 'Madden NFL 2005', 'c09' ],
  [ 'Pokmon Dash', 'c010' ],
  [ 'Dynasty Warriors', 'c011' ],
  [ 'Feel the Magic XY/XX', 'c012' ],
  [ 'Ridge Racer DS', 'c013' ],
  [ 'Darkstalkers Chronicle: The Chaos Tower', 'c014' ],
  [ 'Ape Escape Academy', 'c015' ],
  [ 'Polarium', 'c016' ],
  [ 'Asphalt: Urban GT', 'c017' ],
  [ 'Zoo Keeper', 'c018' ],
  [ 'Mr. DRILLER: Drill Spirits', 'c019' ],
  [ 'Sprung', 'c020' ],
  [ 'Armored Core: Formula Front - Extreme Battle', 'c021' ],
  [ 'Puyo Pop Fever', 'c022' ],
  [ 'Mario Kart DS', 'c023' ],
  [ 'Nintendogs', 'c024' ]
]